rules:
  type-case: [2, always, lower-case]
  type-empty: [2, never]
  type-enum:
    [
      2,
      always,
      [build, ci, chore, docs, feat, fix, perf, refactor, revert, style, test],
    ]
  scope-enum: [0]
  scope-case: [0]
  scope-empty: [0]

  subject-case: [0]
  subject-empty: [2, never]
  subject-full-stop: [2, never, .]

  header-max-length: [2, always, 72]
  body-leading-blank: [2, always]
  footer-leading-blank: [2, always]
