name: Test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
    branches:

jobs:
  formatting:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - run: pnpm install
      - run: npx --no-install prettier --cache --verbose --check .

  type-checking:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        ts-version:
          [5.0.x, 5.1.x, 5.2.x, 5.3.x, 5.4.x, 5.5.x, 5.6.x, 5.7.x, 5.8.x]
        react-version: [18.x, 19.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Typescript ${{ matrix.ts-version }} & React ${{ matrix.react-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'
      - run: |
          pnpm install
          pnpm add -D \
            typescript@${{ matrix.ts-version }} \
            @types/react@${{ matrix.react-version }} \
            @types/react-dom@${{ matrix.react-version }}
      - run: npx --no-install tsc --noEmit

  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        react-version: [18.x, 19.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }} & React ${{ matrix.react-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version: ${{ matrix.node-version }}
      - run: |
          pnpm install
          pnpm add -D \
            react@${{ matrix.react-version }} \
            react-dom@${{ matrix.react-version }} \
            react-test-renderer@${{ matrix.react-version }}
      - run: pnpm run test
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/master' && strategy.job-index == 0
        with:
          name: coverage
          path: coverage
          if-no-files-found: error
          retention-days: 1

  coverage:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage
      - uses: codecov/codecov-action@v5
